import re, json, time, traceback
import app.services.db as db
from app.services.ai import ai_manager
from app.utils.helpers import get_current_slot
from app.core.state import metrics

SYNONYM_MAP = None

def init_synonyms():
    s_map = {
        "xerox": ["printer", "photocopy", "print", "printout"],
        "food": ["canteen", "lunch", "breakfast", "snack", "eat", "hungry", "menu"],
        "teacher": ["professor", "faculty", "timetable", "sir", "ma'am"],
    }
    
    for code, details in db.timetable_data.get("teachers", {}).items():
        full_name = details.get("name", "")
        subject = details.get("subject", "")
        
        clean_parts = [p.lower() for p in full_name.replace(".", "").split() if p.lower() not in ["mr", "ms", "mrs", "dr"]]
        ignore_words = {"engineering", "fundamentals", "basic", "and", "of", "course", "universal", "human", "i", "ii"}
        subject_parts = [s.lower().strip(',.') for s in subject.split() if s.lower().strip(',.') not in ignore_words and len(s) > 2]
        triggers = [code.lower()] + clean_parts + subject_parts
        expanded_info = [full_name, code, subject]
        
        for trigger in triggers:
            if not trigger or len(trigger) < 2: continue
            if trigger not in s_map:
                s_map[trigger] = []
            for info in expanded_info:
                if info and info not in s_map[trigger]:
                    s_map[trigger].append(info)
    return s_map

def expand_query(question):
    global SYNONYM_MAP
    if SYNONYM_MAP is None:
        SYNONYM_MAP = init_synonyms()
        
    lower_q = question.lower()
    expanded_terms = set()
    for key, synonyms in SYNONYM_MAP.items():
        if re.search(rf'\b{re.escape(key)}\b', lower_q):
            expanded_terms.update(synonyms)
    if expanded_terms:
        return question + f"\n[System Note: Consider these hidden keywords for retrieval: {', '.join(expanded_terms)}]"
    return question

def ask(question):
    raw_question = question
    expanded_question = expand_query(question)
    day, slot = get_current_slot()
    
    q_lower = expanded_question.lower()
    context_parts = []

    if any(w in q_lower for w in ['canteen', 'food', 'eat', 'lunch', 'menu', 'cheap', 'price', 'meal', 'snack', 'breakfast']):
        context_parts.append(f"CANTEEN:{json.dumps(db.canteen_data, separators=(',',':'))}")

    if any(w in q_lower for w in ['teacher', 'professor', 'sir', 'ma\'am', 'maam', 'faculty', 'timetable', 'class', 'room', 'slot', 'lecture', 'mj', 'mugdha']):
        context_parts.append(f"TIMETABLE_TODAY:{json.dumps(db.timetable_data.get('timetable', {}).get(day, {}), separators=(',',':'))}")

    if any(w in q_lower for w in ['xerox', 'print', 'photocopy', 'copy', 'printout']):
        context_parts.append(f"XEROX:{json.dumps(db.xerox_data, separators=(',',':'))}")

    if any(w in q_lower for w in ['vend', 'vending', 'machine', 'chips', 'cold drink', 'snack', 'drinks']):
        context_parts.append(f"VENDING:{json.dumps(db.vending_data, separators=(',',':'))}")

    if any(w in q_lower for w in ['event', 'workshop', 'seminar', 'fest', 'competition', 'happening', 'week']):
        context_parts.append(f"EVENTS:{json.dumps(db.events_data, separators=(',',':'))}")

    if db.community_data.get('facts'):
        context_parts.append(f"COMMUNITY FACTS:{json.dumps(db.community_data['facts'], separators=(',',':'))}")

    if not context_parts:
        context_parts.append("You can answer general campus questions. If info not found, suggest admin office or notice board.")

    context = "\n".join(context_parts)

    system_prompt = f"""You are AskVES, a helpful AI assistant for VESIT college students. Be concise.
Today is {day}, current slot: {slot} (None = break or outside hours).
{context}
For teacher queries: find their code, check today's timetable for current slot, return room and division.
If info not found: suggest admin office or notice board."""

    current_message = {"role": "user", "content": expanded_question}
    messages = [{"role": "system", "content": system_prompt}, current_message]
    
    try:
        start_time = time.time()
        answer, provider = ai_manager.generate(messages)
        
        metrics["total_queries"] += 1
        metrics["total_response_time"] += (time.time() - start_time)
        metrics["provider_usage"][provider] = metrics["provider_usage"].get(provider, 0) + 1
        
        print(f"✓ Response generated by: {provider}")
        return answer
        
    except Exception as e:
        error_msg = str(e)
        print(f"✗ All AI providers failed: {error_msg}")
        print(f"✗ Traceback: {traceback.format_exc()}")
        print(f"✗ Available providers at time of error: {list(ai_manager.providers.keys())}")
        return "Sorry, I'm having trouble right now. Try again in a minute! 🙏"
